services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - app-network
    env_file:
      - .env

  web:
    build:
      context: ./ChatProject  # Set context to ChatProject directory
      dockerfile: ./Dockerfile  # Specify relative path to Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 ChatProject.asgi:application"
    volumes:
      - ./ChatProject:/app  # Mount ChatProject directory to /app in container
      - static_volume:/app/static
      - media_volume:/app/media  # Add media volume if you need to handle uploads

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume: 

networks:
  app-network:
